### ISSUE TITLE
Wired Problem in MY IDEA

### ISSUE THREAD

**Issue by langren1353** [wenzewoo/jetbrains-markdown-image-support#1]
非常感谢老大哥的插件，功能很强大，不过个人在使用的过程中遇到了一点小小的问题：Ctrl+V功能在部分弹出层窗口中无效：
OS: Windows 10 1024
Software: IDEA 2020.2 JetBrains
Problems: 
Install this plugin and problems will happen when I do `copy and paste` in any dialog, paste will not functional.
Ctrl+V not functional, Ctrl+Shift+Alt+V is OK.
dialog show when : `Ctrl+Shift+F` or `new FIle Dialog`
Hope this will be better in the future.

**Comment by wenoptics** [comment]
Same issue here. The paste won't work with the plugin enabled. (e.g. Can not paste in the commit dialog or docked commit panel)

On 

> PyCharm 2020.2.3 (Professional Edition)
Build #PY-202.7660.27, built on October 6, 2020
Runtime version: 11.0.8+10-b944.34 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 725M
Cores: 12
Registry: ide.images.show.chessboard=true
Non-Bundled Plugins: Batch Scripts Support, CMD Support, com.github.wenzewoo.jetbrains.plugin.jetbrains-markdown-image-support, com.jetbrains.intellij.datalore, com.github.nokia.pyvenv, ru.meanmail.plugin.requirements

**Comment by remember-5** [comment]
同遇到这个问题，感谢老哥的插件，好评

**Comment by wenzewoo** [comment]
Fixed.
